name: Build check

# Branch (Ignoring) [main]
# - Build app assets
# |-- Lint project
# |-- Run Tests

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:


jobs:
  setup:
    name: Setup code and environment needed for linting and tests
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --immutable # will run `yarn install` command
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  lint:
    runs-on: self-hosted
    needs: setup
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Restore node modules from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - run: mkdir -p ~/reports
      - name: Lint
        uses: borales/actions-yarn@v5
        with:
          cmd: lint
      - name: Upload linting report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: ~/reports/eslint.xml

  test:
    runs-on: macos-latest
    needs: setup
    timeout-minutes: 20
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Restore node modules from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Run tests with JUnit as reporter
        uses: borales/actions-yarn@v5
        with:
          cmd: test
        env:
          JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - name: Upload Jest JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: jest-test-results
          path: ./reports/junit/junit.xml
